### ISSUE TITLE
Not able to add keys in source language file

### ISSUE THREAD

**Issue by djbisht** [ibm-cloud-docs/GlobalizationPipeline#2]
Hi,
I have one node applicaiton which is using gpclient to process bundle for language translation. I have uploaded json format.Globalizaiton pipelien is restricting us to add more keys in json file as we already had 1000 keys in it. Our applicaiton is having n numbr of keys.How can we resolve this issue.

**Comment by srl295** [comment]
@djbisht Sorry, this repository is only for documentation. Please open a support issue through the IBM Cloud console. Thanks.

**Comment by liuxjep** [comment]
@srl295 Thanks, Steven. Closing this issue...
